### ISSUE TITLE
No source code published

### ISSUE THREAD

**Issue by alfishe** [hypercomments-hq/hypercomments-issues#1]
This is #1 conceptual issue. Otherwise this is not a project for GitHub and wastes resources

**Comment by anurbol** [comment]
@alfishe Thank you, Ilia for your interest in the project. First thing, there are many other issue-only repos here at GitHub, so this is not unique to my project. There are no official restrictions from GitHub on this. That said, I do plan to publish the source and make it open, but not too soon. Maybe in a few months, depends on how things are going to go. The reason, that the source is private for now, is that making it open source and maintaining as such requires significant effort, and currently I don't have resources to do that. Another reason is, I want to have at least some advantage to be in control of the new software, forks is not what I or HyperComments need right now. Yet another reason is that open source doesn't automatically mean that someone's  going to contribute, actually people may [distract even more than they contribute](https://words.steveklabnik.com/a-sad-day-for-rust). 

Again, thank you for your interest! Some day this will inevitably become open source, because any software will be either open source or dead, eventually, I understand this very well.
